version: '3'
services:
    pgsql:
        image: 'postgres:13'
        container_name: pgsql
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        networks:
            - aquatools

    at_backend:
        build:
            context: .
            dockerfile: Dockerfile

        image: at_backend
        container_name: at2_backend
        ports:
            - 8000:8000
        # command: bash -c "php artisan migrate"
        volumes:
            - .:/var/www/html
        networks:
            - aquatools
        depends_on:
            - pgsql



networks:
    aquatools:
        driver: bridge